name: Android CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Create Const
      run: echo '${{ secrets.CONST }}' > ./app/src/main/java/com/juniori/puzzle/app/util/Const.kt

    - name: Create GOOGLE_SERVICES_JSON
      run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > ./app/google-services.json

    # Build Debug App
    - name: Build with Gradle
      run: ./gradlew assembleDebug
      
    # Run unit test
    - name: Run unit test
      run: ./gradlew testdebugUnitTest
